### ISSUE TITLE
Composer Installer

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#1]
## Technical Story

A content block package should be installed via composer.

### Acceptance criteria

- [x]  `composer require some-vendor/some-content-block` installs the package of type `typo3-cms-contentblock` into `typo3conf/contentBlocks/` (replace "some-vendor" with the vendor and "some-content-block" with the name of the package)
- [ ] *technically not possible* The Content Block is only installed if valid

**Comment by jonaseberle** [comment]
The criteria "The Content Block is only installed if valid" is hard to achieve in a composer plugin. 

Currently we only answer composer's question "Where should this package of type `typo3-cms-contentblock` be installed to"? 
The decision for symlinking/copying etc. is then up to composer. 

Maybe the package is not even downloaded so we would not be able to inspect it at that point but I would have to check.

Since the main use case will probably be a local composer repository with contentBlocks it can be expected that contentBlock code changes after composer installation - which would then be totally out of reach for the composer plugin.

We certainly can check it though when building our configuration.
What do you think? Would that be enough?
