### ISSUE TITLE
Generate TypoScript config based on the EditorInterface.yaml of the Content Block package

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#2]
## Technical Story
Generate TypoScript config out of the EditorInterface.yaml of the Content Block package.

### Acceptance criteria

- [x] The CType is created based on the vendor and package name (e.g. vendor_packagename)
- [x] The CType inherits from `lib.contentElement`
- [x] Root paths for layouts, templates and partials are set for the CType
- [x] The template name for the CType is set to `Frontend.html`
- [x] The preview template for the CType is set to `EditorPreview.html` of the Content Block package

**Comment by typecat** [comment]
I would postpone the usage of DataProcessors to a different milestone.

**Comment by krausandre** [comment]
Notes:

- We can add DataProcessors actually to a content block by adding them in a sitepackage or any extension, which depends on the registration API or the content block. We think this should work.

- "The CType inherits from lib.contentElement" -> it does, but we actually didn't manage, that fluid styled content is loaded before the registration API. We could,, if we set fluid styled content as required, but after that content blocks aren't no more independent. I think this is not acceptable.

**Comment by jonaseberle** [comment]
We currently load lib.contentElement via `@import` in our ext_localconf.php.

In order to be able to provide a fallback for the Layout, we needed to use `-5` as key in layoutRootPaths. (this seems to work but we are unsure if that is official API)

This would work with:
* fsc + Templates with <f:layout Default>
* no fsc + Templates with <f:layout Default>
* no fsc without Templates with <f:layout Default>


Mask:
https://docs.typo3.org/p/mask/mask/6.2/en-us/Installation/Index.html?highlight=fluid_styled_content
https://docs.typo3.org/p/mask/mask/6.2/en-us/Pagetemplates/Index.html?highlight=fluid_styled_content

**Comment by jonaseberle** [comment]
I'll close this in favor of

https://github.com/TYPO3-Initiatives/content-block-registration-api/issues/27

and 

https://github.com/TYPO3-Initiatives/content-block-registration-api/issues/29
