### ISSUE TITLE
Enable usage of collection field type in EditorInterface.yaml of the Content Block package

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#21]
## Technical Story

Enable usage of collection field type in EditorInterface.yaml of the Content Block package

### Acceptance criteria

- [x] Field type 'collection' can be used for inline relations in a content block

**Comment by jonaseberle** [comment]
Example for using `<section>` - that's currently implemented via 616fb0a141d6331286da35fe1ba61bf09b045ce9
Unfortunately it does not support 
* sub-levels (section in section)
* inline (e.g. FAL-files)

**Comment by krausandre** [comment]
It is not possible to use sections, because it is not allowed to nest elements of type "inline" or "section" in flexform sections. This means, e. g. for the slider example, that you are not allowed to use an image in a slide. Not really helpful I guess.
[Documentation on that](https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/Flex.html#flexform-syntax) 

So the solution is to use a foreign table for the collections as field type inline. This allows us to nest other inline stuff, so we can nest collections in collections or images or what ever we want to nest.

**Comment by jonaseberle** [comment]
This is now implemented with an inline relation pointing to a record in a foreign table. The TCA for that table holds another flexform field that uses a `ds_pointer` to select the FlexForm for the current CType AND field name. 

Collections can now be nested and mixed with Images on any level.

We did not test language handling and workspaces yet. I opened https://github.com/TYPO3-Initiatives/content-block-registration-api/issues/32 for that.
