### ISSUE TITLE
Validate the EditorInterface.yaml of a Content Block package

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#8]
## Technical Story

Validate the `EditorInterface.yaml` of a Content Block package

### Acceptance criteria

- [x] The file defines the editor interface of exactly one content block
- [x] At least one field is defined
- [x] The fields are only of types and have only properties defined in the [documentation](https://github.com/TYPO3-Initiatives/structured-content/blob/master/Documentation/ContentBlocks/FieldTypeMapping.md)
- [ ] The YAML file contents are validated against a JSON schema

**Comment by typecat** [comment]
Can also be partly done for v2.

**Comment by krausandre** [comment]
TODO: The fields are only of types and have only properties defined in the [documentation](https://github.com/TYPO3-Initiatives/structured-content/blob/master/Documentation/ContentBlocks/FieldTypeMapping.md)

-> Conclusion: Since the system ignores not matching types and properties, this is not necessary.

____

TODO: The YAML file contents are validated against a JSON schema

-> Not clear what to do here and if necessary.  
-> Tough to implement and less benefit though
-> Suggestion: omit this or do that later

**Comment by typecat** [comment]
>The YAML file contents are validated against a JSON schema

Moved this into an own issue for further evaluation: #88
